### ISSUE TITLE
Brainstorm of New "The Gun" For Controlling Brushless Motors

### ISSUE THREAD

**Issue by johnthibert** [frc5885/FRC5885Mechanical#1]
We need to brainstorm ideas/features/characteristics of how we want to build this.
 
Some questions we may need to initially answer are:

1. How many motors do we want to run?
2. Do we want to be able to power Falcons?
3. Do we want to be able to control regular DC motors?
4. How do we want to power this? Robot battery or something else?
5.  ETC

Come up with initial ideation drawings and things we may need to build this.

Assigned to all of mechanical!!!

**Comment by zjs0221** [comment]
**Link to Chief Delphi:**
[https://www.chiefdelphi.com/t/brushless-motor-controller-tester/392593/22?page=2](url)

**Ideas:**

- Make a single motor gun (drill style) and a 5-motor control panel (similar to a light or sound board)
- Use Arduino (or alternative analogue to PWM converter) for gun and RIO for panel
- Make the panel first (maybe try prototyping) as RIO can definitely do everything necessary. (This can help us identify all the functions we need and what we need to buy.)

**Questions:**
1. How many motors do we want to run?

> Both a single motor and many at the same time (5?)

2. Do we want to be able to power Falcons?

> Yes

3. Do we want to be able to control regular DC motors?

> Probably? We do have a lot of them if we want to do separate prototypes to test many ideas at once.

4. How do we want to power this? Robot battery or something else?

> Definitely robot battery for the panel, maybe drill battery for handheld.

**Tasks:**

- [ ] Research brushless motors, SPARK MAXes, and Falcons
- [ ] Find analogue to PWM converter
- [ ] Create concept sketches
- [ ] Locate all necessary components
- [ ] Create CAD model
- [ ] Build!

**Comment by h0im3die** [comment]
The only problem I would see with using a drill battery over a robot battery is amperage. Most drill battery's cant supply even 20 amps, let alone the 40 amps we run most of our motors at.

**Comment by marcotron64** [comment]
June 4th Meeting Summary

- It will be able to use both 18V drill batteries and 12V robot batteries (make adapter from robot battery to drill battery connector)
- We will be using the shell of Zero To Hero
- Using the original drill trigger as analog input, and the drill direction selector to switch polarity
- Using Arduino Nano to generate PWM signal from analog voltage
- Buck converter to power Arduino off of drill battery

Outputs needed:
- Power passthrough (Falcon)
- PWM passthrough (Falcon)
- Anderson and Wago (Sparkmax)

To-Do:
- Wiring diagram
- Drill front plate
- Robot battery to drill battery adapter

**Comment by johnthibert** [comment]
Proof as to what I mentioned at the meeting yesterday (wanted to see what he'd say):
![Image](https://github.com/frc5885/FRC5885Mechanical/assets/84032459/886278d9-6c09-49ae-8c8e-31d80118539f)

**Comment by quizque** [comment]
If you need bucks I have a box full that work up to I think 30v. I can bring them Thursday. The resister divider would probably still work but it might brown out lol.On Jun 5, 2024, at 7:15 AM, John Thibert ***@***.***> wrote:﻿
Proof as to what I mentioned at the meeting yesterday (wanted to see what he'd say):
image.png (view on web)
